AWSTemplateFormatVersion: 2010-09-09
Description: >-
  sam-app
Transform:
  - AWS::Serverless-2016-10-31

Parameters:
  ProjectName:
    Type: String
    Default: "lambda-sam-playwright-v2"
  CreatedBy:
    Type: String
    Default: "sam-cli"
  Env:
    Type: String
    AllowedValues:
      - prd
      - stg
      - local

# https://docs.aws.amazon.com/ja_jp/serverless-application-model/latest/developerguide/sam-specification-template-anatomy-globals.html
Globals:
  Function:
    Tracing: Active
    Runtime: &nodejsRuntime nodejs22.x
    Architectures:
      # Armを使用したいが、@sparticuz/chromium@141がarmをサポートしていないため、x86_64を指定
      - &chromiumArch x86_64
    Handler: index.handler
    MemorySize: 128
    Timeout: 3
    LoggingConfig:
      LogFormat: JSON
    EventInvokeConfig:
      MaximumRetryAttempts: 0
    Environment:
      Variables:
        NODE_OPTIONS: --enable-source-maps
        ENV: !Ref Env
    Tags:
      Project: !Ref ProjectName
      CreatedBy: !Ref CreatedBy
  Api:
    TracingEnabled: true
    # Stageの生成を無効化するために設定、OpenAPIは使用していない: https://docs.aws.amazon.com/ja_jp/serverless-application-model/latest/developerguide/sam-resource-api.html#sam-api-openapiversion
    OpenApiVersion: 3.0.2

# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html
Resources:
  # ---- ChromiumLayer Layer start ----
  # https://github.com/Sparticuz/chromium/blob/dd57f035695c6773e17768176bda1910b1e39287/examples/aws-sam/template.yml
  ChromiumLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      Description: Chromium with Node.js integration for AWS Lambda
      ContentUri: src/layers/chromium
      CompatibleRuntimes:
        - *nodejsRuntime
      CompatibleArchitectures:
        - *chromiumArch
      RetentionPolicy: Delete
    Metadata:
      BuildMethod: *nodejsRuntime
      BuildArchitecture: *chromiumArch
  # ---- ChromiumLayer Layer end ----

  # ---- NotoSansJPLayer Layer start ----
  NotoSansJPLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: noto-sans-jp
      Description: NotoSansJP font for Chromium
      ContentUri: src/layers/font
      CompatibleRuntimes:
        - nodejs22.x
      CompatibleArchitectures:
        - arm64
      RetentionPolicy: Delete
  # ---- NotoSansJPLayer Layer end ----

  # ---- ApiHealthcheck Function start ----
  ApiHealthcheckFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${ProjectName}-${Env}-healthcheck"
      Description: Healthcheck function
      Events:
        Api:
          Type: Api
          Properties:
            Path: /api/healthcheck
            Method: GET
    Metadata:
      BuildMethod: makefile
  ApiHealthcheckFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${ApiHealthcheckFunction}
      RetentionInDays: 90
  # ---- ApiHealthcheck Function end ----

  # ---- ApiV1Snapshot Function start ----
  ApiV1SnapshotFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${ProjectName}-${Env}-v1-snapshot"
      Description: V1 snapshot function
      Environment:
        Variables:
          PLAYWRIGHT_RUNNER_FUNCTION_NAME: !Sub "${ProjectName}-${Env}-playwright-runner"
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - lambda:InvokeFunction
              Resource: !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${ProjectName}-${Env}-playwright-runner"
      Events:
        Api:
          Type: Api
          Properties:
            Path: /api/v1/snapshot
            Method: POST
    Metadata:
      BuildMethod: makefile
  ApiV1SnapshotFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${ApiV1SnapshotFunction}
      RetentionInDays: 90
  # ---- ApiV1Snapshot Check Function end ----

  # ---- Playwright Runner Function start ----
  PlaywrightRunnerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${ProjectName}-${Env}-playwright-runner"
      Description: Playwright runner function
      Timeout: 300 # 5分
      MemorySize: 2048 # 2GB
      Layers:
        - !Ref ChromiumLayer
        - !Ref NotoSansJPLayer
      Environment:
        Variables:
          S3_DEST_BUCKET_NAME: !Sub "${ProjectName}-${Env}-snapshot"
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - s3:PutObject
              Resource: !Sub "arn:aws:s3:::${ProjectName}-${Env}-snapshot/*"
    Metadata:
      BuildMethod: makefile
  PlaywrightRunnerFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${PlaywrightRunnerFunction}
      RetentionInDays: 90
  # ---- Playwright Runner Function end ----

  # ---- S3 Bucket for Snapshot start ----
  S3SnapshotBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${ProjectName}-${Env}-snapshot"
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: CreatedBy
          Value: !Ref CreatedBy
      LifecycleConfiguration:
        Rules:
          - Status: Enabled
            ExpirationInDays: 90
  S3SnapshotBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3SnapshotBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Principal:
              Service: cloudfront.amazonaws.com
            Action:
              - s3:GetObject
            Effect: Allow
            Resource:
              - !Sub ${S3SnapshotBucket.Arn}/*
            Condition:
              StringEquals:
                AWS:SourceArn:
                  - !Sub arn:aws:cloudfront::${AWS::AccountId}:distribution/${CloudFrontSnapshotDistribution}
  # ---- S3 Bucket for Snapshot end ----

  # ---- CloudFront Distribution for Snapshot start ----
  CloudFrontSnapshotDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Comment: Snapshot distribution with API Gateway
        DefaultCacheBehavior:
          TargetOriginId: S3SnapshotBucketOrigin
          Compress: true
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
          CachedMethods:
            - GET
            - HEAD
          # CloudFront標準キャッシュポリシーID: CachingOptimized
          # https://docs.aws.amazon.com/ja_jp/AmazonCloudFront/latest/DeveloperGuide/using-managed-cache-policies.html#managed-cache-caching-optimized
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
          # CloudFront標準オリジンリクエストポリシーID: CORS-S3Origin
          # https://docs.aws.amazon.com/ja_jp/AmazonCloudFront/latest/DeveloperGuide/using-managed-origin-request-policies.html#managed-origin-request-policy-cors-s3
          OriginRequestPolicyId: 88a5eaf4-2fd4-4709-b370-b4c650ea3fcf
        CacheBehaviors:
          - PathPattern: /api/*
            TargetOriginId: ApiGatewayOrigin
            ViewerProtocolPolicy: redirect-to-https
            AllowedMethods:
              - GET
              - HEAD
              - OPTIONS
              - PUT
              - POST
              - PATCH
              - DELETE
            CachedMethods:
              - GET
              - HEAD
            # CloudFront標準キャッシュポリシーID: CachingDisabled
            # https://docs.aws.amazon.com/ja_jp/AmazonCloudFront/latest/DeveloperGuide/using-managed-cache-policies.html#managed-cache-policy-caching-disabled
            CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad
            # CloudFront標準オリジンリクエストポリシーID: AllViewerExceptHostHeader
            # https://docs.aws.amazon.com/ja_jp/AmazonCloudFront/latest/DeveloperGuide/using-managed-origin-request-policies.html#managed-origin-request-policy-all-viewer-except-host-header
            OriginRequestPolicyId: b689b0a8-53d0-40ab-baf2-68738e2966ac
        PriceClass: PriceClass_200
        DefaultRootObject: index.html
        Enabled: true
        Origins:
          - DomainName: !GetAtt S3SnapshotBucket.RegionalDomainName
            Id: S3SnapshotBucketOrigin
            OriginAccessControlId: !GetAtt S3SnapshotBucketOriginAccessControl.Id
            S3OriginConfig:
              OriginAccessIdentity: ""
          - DomainName: !Sub "${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com"
            Id: ApiGatewayOrigin
            OriginPath: "/Prod"
            CustomOriginConfig:
              OriginProtocolPolicy: https-only
  S3SnapshotBucketOriginAccessControl:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        SigningBehavior: always
        OriginAccessControlOriginType: s3
        SigningProtocol: sigv4
        Name: !Sub ${AWS::StackName}-OAC-${AWS::AccountId}
  # ---- CloudFront Distribution for Snapshot end ----

  # ---- Static Deployment IAM User ----
  StaticDeploymentUser:
    Type: AWS::IAM::User
    Properties:
      UserName: !Sub "${ProjectName}-${Env}-static-deployment-user"
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: CreatedBy
          Value: !Ref CreatedBy
  StaticDeploymentUserAccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref StaticDeploymentUser
  StaticDeploymentUserPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub "${ProjectName}-${Env}-static-deployment-policy"
      Users:
        - !Ref StaticDeploymentUser
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - s3:PutObject
            Resource:
              - !Sub "arn:aws:s3:::${S3SnapshotBucket}/*"
          - Effect: Allow
            Action:
              - cloudfront:CreateInvalidation
            Resource:
              - !Sub "arn:aws:cloudfront::${AWS::AccountId}:distribution/${CloudFrontSnapshotDistribution}"
  # ---- Static Deployment IAM User end ----

Outputs:
  ApiV1HealthcheckFunctionApi:
    Description: "API Gateway URL for ApiV1HealthcheckFunction"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/api/v1/healthcheck"
  ApiV1SnapshotFunctionApi:
    Description: "API Gateway URL for ApiV1SnapshotFunction"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/api/v1/snapshot"
  StaticDeploymentUserAccessKeyId:
    Description: "Access Key ID for Static Deployment User"
    Value: !Ref StaticDeploymentUserAccessKey
  StaticDeploymentUserSecretAccessKey:
    Description: "Secret Access Key for Static Deployment User"
    Value: !GetAtt StaticDeploymentUserAccessKey.SecretAccessKey
