name: "Setup"
description: "Setup AWS SAM CLI"

runs:
  using: composite
  steps:
    # https://docs.aws.amazon.com/ja_jp/serverless-application-model/latest/developerguide/deploying-using-github.html
    - uses: actions/setup-python@v6
    - uses: aws-actions/setup-sam@v2
    # - uses: aws-actions/configure-aws-credentials@v5
    #   with:
    #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #     aws-region: ap-northeast-1
